In [1]:
import sys
sys.path.append(".")
sys.path.append("..")

In [6]:
import os
import skimage
import numpy as np
import pandas as pd

from defaults.bases import *
import h5py

# JUMP

In [1]:
root = "/raid/user/data/JUMP/cpg0004-lincs/inputs_224/"
df = pd.read_csv("/raid/user/data/JUMP/cpg0004-lincs/metadata/df_withDMSO_withCrops_filtered_v3.csv")

NameError: name 'pd' is not defined

In [9]:
def get_image(root_dir, img_paths):
    full = np.zeros((224, 224, 5))
    for i, path in enumerate(img_paths.split(",")):
        full[:, :, i] = skimage.io.imread(root_dir + path)
    return full

In [7]:
df_dmso = df[df["Compound"] != "DMSO"].reset_index(drop=True)

In [8]:
df_dmso

,Unnamed: 0,Metadata_Plate,Metadata_Well,Metadata_Site,Metadata_broad_sample,Metadata_moa,Metadata_mmoles_per_liter,Metadata_dose_recode,RNA,ER,...,Treatment,Plate_Map_Name,Split,Metadata_broad_sample_ID,Metadata_moa_ID,Metadata_Plate_ID,replicate_ID,combined_paths,Unique_well,crops
0,0,SQ00014812,A07,1,BRD-K74363950-004-01-0,acetylcholine receptor antagonist,10.0,6,SQ00014812/r01c07f01p01-ch3sk1fk1fl1.tiff,SQ00014812/r01c07f01p01-ch2sk1fk1fl1.tiff,...,BRD-K74363950-004-01-0@9.99999999999999999,C-7161-01-LM6-022,Training,1259,16,0,1.0,"SQ00014812/r01c07f01p01-ch1sk1fk1fl1.png,SQ000...",SQ00014812-A07,"[[8, 710], [11, 856], [14, 839], [19, 646], [1..."
1,1,SQ00014812,A07,2,BRD-K74363950-004-01-0,acetylcholine receptor antagonist,10.0,6,SQ00014812/r01c07f02p01-ch3sk1fk1fl1.tiff,SQ00014812/r01c07f02p01-ch2sk1fk1fl1.tiff,...,BRD-K74363950-004-01-0@9.99999999999999999,C-7161-01-LM6-022,Training,1259,16,0,1.0,"SQ00014812/r01c07f02p01-ch1sk1fk1fl1.png,SQ000...",SQ00014812-A07,"[[13, 655], [14, 184], [17, 475], [18, 109], [..."
2,2,SQ00014812,A07,3,BRD-K74363950-004-01-0,acetylcholine receptor antagonist,10.0,6,SQ00014812/r01c07f03p01-ch3sk1fk1fl1.tiff,SQ00014812/r01c07f03p01-ch2sk1fk1fl1.tiff,...,BRD-K74363950-004-01-0@9.99999999999999999,C-7161-01-LM6-022,Training,1259,16,0,1.0,"SQ00014812/r01c07f03p01-ch1sk1fk1fl1.png,SQ000...",SQ00014812-A07,"[[16, 112], [15, 246], [15, 598], [19, 929], [..."
3,3,SQ00014812,A07,4,BRD-K74363950-004-01-0,acetylcholine receptor antagonist,10.0,6,SQ00014812/r01c07f04p01-ch3sk1fk1fl1.tiff,SQ00014812/r01c07f04p01-ch2sk1fk1fl1.tiff,...,BRD-K74363950-004-01-0@9.99999999999999999,C-7161-01-LM6-022,Training,1259,16,0,1.0,"SQ00014812/r01c07f04p01-ch1sk1fk1fl1.png,SQ000...",SQ00014812-A07,"[[18, 1041], [14, 788], [17, 861], [19, 775], ..."
4,4,SQ00014812,A07,5,BRD-K74363950-004-01-0,acetylcholine receptor antagonist,10.0,6,SQ00014812/r01c07f05p01-ch3sk1fk1fl1.tiff,SQ00014812/r01c07f05p01-ch2sk1fk1fl1.tiff,...,BRD-K74363950-004-01-0@9.99999999999999999,C-7161-01-LM6-022,Training,1259,16,0,1.0,"SQ00014812/r01c07f05p01-ch1sk1fk1fl1.png,SQ000...",SQ00014812-A07,"[[18, 769], [17, 974], [24, 959], [26, 424], [..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24516,24590,SQ00015233,O13,5,BRD-K41160163-001-06-8,glutamate receptor antagonist,10.0,6,SQ00015233/r15c13f05p01-ch3sk1fk1fl1.tiff,SQ00015233/r15c13f05p01-ch2sk1fk1fl1.tiff,...,BRD-K41160163-001-06-8@9.99999999999999999,C-7161-01-LM6-014,Test,821,32,135,5.0,"SQ00015233/r15c13f05p01-ch1sk1fk1fl1.png,SQ000...",SQ00015233-O13,"[[37, 956], [44, 1021], [87, 926], [100, 934],..."
24517,24591,SQ00015233,O13,6,BRD-K41160163-001-06-8,glutamate receptor antagonist,10.0,6,SQ00015233/r15c13f06p01-ch3sk1fk1fl1.tiff,SQ00015233/r15c13f06p01-ch2sk1fk1fl1.tiff,...,BRD-K41160163-001-06-8@9.99999999999999999,C-7161-01-LM6-014,Test,821,32,135,5.0,"SQ00015233/r15c13f06p01-ch1sk1fk1fl1.png,SQ000...",SQ00015233-O13,"[[18, 968], [15, 42], [21, 549], [25, 29], [24..."
24518,24592,SQ00015233,O13,7,BRD-K41160163-001-06-8,glutamate receptor antagonist,10.0,6,SQ00015233/r15c13f07p01-ch3sk1fk1fl1.tiff,SQ00015233/r15c13f07p01-ch2sk1fk1fl1.tiff,...,BRD-K41160163-001-06-8@9.99999999999999999,C-7161-01-LM6-014,Test,821,32,135,5.0,"SQ00015233/r15c13f07p01-ch1sk1fk1fl1.png,SQ000...",SQ00015233-O13,"[[10, 823], [16, 192], [13, 806], [14, 1001], ..."
24519,24593,SQ00015233,O13,8,BRD-K41160163-001-06-8,glutamate receptor antagonist,10.0,6,SQ00015233/r15c13f08p01-ch3sk1fk1fl1.tiff,SQ00015233/r15c13f08p01-ch2sk1fk1fl1.tiff,...,BRD-K41160163-001-06-8@9.99999999999999999,C-7161-01-LM6-014,Test,821,32,135,5.0,"SQ00015233/r15c13f08p01-ch1sk1fk1fl1.png,SQ000...",SQ00015233-O13,"[[12, 595], [21, 562], [21, 582], [27, 678], [..."
24520,24594,SQ00015233,O13,9,BRD-K41160163-001-06-8,glutamate receptor antagonist,10.0,6,SQ00015233/r15c13f09p01-ch3sk1fk1fl1.tiff,SQ00015233/r15c13f09p01-ch2sk1fk1fl1.tiff,...,BRD-K41160163-001-06-8@9.99999999999999999,C-7161-01-LM6-014,Test,821,32,135,5.0,"SQ00015233/r15c13f09p01-ch1sk1fk1fl1.png,SQ000...",SQ00015233-O13,"[[26, 158], [52, 62], [55, 92], [68, 62], [75,..."

In [24]:
mean_columns = ["mean_" + str(x) for x in range(5)]
std_columns  = ["std_"  + str(x) for x in range(5)]

mean, std, plates = [], [], []
for p in df_dmso["Metadata_Plate"].unique():
    print(p)
    means = [[] for i in range(5)]
    stds = [[] for i in range(5)]
    
    for idx, row in df_dmso[df_dmso["Metadata_Plate"] == p].iterrows():
        img_path = row["combined_paths"]
        img = get_image(root, img_path)
        
        mean_0, std_0 = np.mean(img[..., 0]), np.std(img[..., 0])
        mean_1, std_1 = np.mean(img[..., 1]), np.std(img[..., 1])
        mean_2, std_2 = np.mean(img[..., 2]), np.std(img[..., 2])
        mean_3, std_3 = np.mean(img[..., 3]), np.std(img[..., 3])
        mean_4, std_4 = np.mean(img[..., 4]), np.std(img[..., 4])

        means[0].append(mean_0)
        stds[0].append(std_0)
        means[1].append(mean_1)
        stds[1].append(std_1)
        means[2].append(mean_2)
        stds[2].append(std_2)
        means[3].append(mean_3)
        stds[3].append(std_3)
        means[4].append(mean_4)
        stds[4].append(std_4)
            
            
    mean.append(np.array(means).mean(axis=1))
    std.append(np.array(stds).mean(axis=1))
    plates.append(row["Metadata_Plate"])

SQ00014812
SQ00014813
SQ00014814
SQ00014815
SQ00015206
SQ00014816
SQ00014817
SQ00014818
SQ00014819
SQ00015207
SQ00014820
SQ00015041
SQ00015042
SQ00015043
SQ00015208
SQ00015044
SQ00015045
SQ00015046
SQ00015047
SQ00015209
SQ00015048
SQ00015049
SQ00015050
SQ00015051
SQ00015210
SQ00015052
SQ00015053
SQ00015054
SQ00015055
SQ00015211
SQ00015056
SQ00015057
SQ00015058
SQ00015059
SQ00015212
SQ00015096
SQ00015097
SQ00015098
SQ00015099
SQ00015204
SQ00015100
SQ00015101
SQ00015102
SQ00015103
SQ00015205
SQ00015105
SQ00015106
SQ00015107
SQ00015108
SQ00015132
SQ00015109
SQ00015110
SQ00015111
SQ00015112
SQ00015133
SQ00015116
SQ00015117
SQ00015118
SQ00015119
SQ00015125
SQ00015120
SQ00015121
SQ00015122
SQ00015123
SQ00015126
SQ00015124
SQ00015127
SQ00015154
SQ00015155
SQ00015156
SQ00015128
SQ00015157
SQ00015158
SQ00015159
SQ00015160
SQ00015129
SQ00015162
SQ00015163
SQ00015164
SQ00015173
SQ00015130
SQ00015165
SQ00015166
SQ00015167
SQ00015168
SQ00015131
SQ00015169
SQ00015170
SQ00015171
SQ00015172
SQ00015134
SQ00015135
SQ00015136
SQ00015137
SQ00015199
SQ00015138
SQ00015139
SQ00015140
SQ00015141
SQ00015200
SQ00015142
SQ00015143
SQ00015144
SQ00015145
SQ00015201
SQ00015146
SQ00015147
SQ00015148
SQ00015149
SQ00015202
SQ00015150
SQ00015151
SQ00015152
SQ00015153
SQ00015203
SQ00015194
SQ00015214
SQ00015215
SQ00015216
SQ00015217
SQ00015195
SQ00015218
SQ00015219
SQ00015220
SQ00015221
SQ00015196
SQ00015222
SQ00015223
SQ00015224
SQ00015197
SQ00015229
SQ00015198
SQ00015230
SQ00015231
SQ00015232
SQ00015233

In [31]:
mean = np.array(mean)
std = np.array(std)

mean = mean.transpose()
std = std.transpose()

In [32]:
d = {
    "Metadata_Plate": plates,
    "DNA_mean": mean[0],
    "ER_mean": mean[1],
    "RNA_mean": mean[2],
    "AGP_mean": mean[3],
    "Mito_mean": mean[4],
    "DNA_std": std[0],
    "ER_std": std[1],
    "RNA_std": std[2],
    "AGP_std": std[3],
    "Mito_std": std[4] 
}

In [35]:
mean[0]

array([13.42566283, 13.70711946, 14.25016305, 14.00380863, 14.84898878,
       13.94775241, 15.21291668, 14.54680101, 14.39148811, 14.16136519,
       15.86535166, 15.47167165, 16.29650831, 15.34083311, 16.15860796,
       14.48522285, 15.3338221 , 16.63125534, 16.04644288, 14.90594353,
       13.8496525 , 14.79270442, 14.69921793, 15.04937474, 16.37260061,
       15.24046819, 15.18624455, 15.32455117, 15.22975531, 16.67144683,
       16.12223972, 15.50810439, 16.14172183, 15.83366121, 16.63528117,
       16.8624517 , 16.80789805, 15.75120354, 16.06323027, 17.1429328 ,
       13.44672789, 13.75586468, 13.84262661, 13.97222124, 14.87260344,
       15.64769997, 14.20787396, 15.1378561 , 14.22685997, 16.95365265,
       13.58899537, 13.5252856 , 12.80645358, 13.14800365, 14.43164773,
       14.27083469, 15.08261804, 15.13683546, 15.62614065, 12.35997775,
       14.27903431, 14.25722793, 15.25274112, 15.37210417, 14.45699871,
       14.46250282, 14.55782894, 14.0614213 , 14.18387996, 15.57487367,
       14.1152723 , 14.17415449, 13.99876115, 14.76437504, 14.55457509,
       14.99814727, 14.83225123, 14.259545  , 14.09029005, 15.32774494,
       15.04591414, 15.71528925, 15.89402277, 15.8863381 , 15.41361203,
       10.98579293, 11.16086996, 11.5992415 , 11.57845038, 11.10829048,
       11.12107773, 12.60693237, 11.5095901 , 11.19980398, 13.63409689,
       14.05445174, 13.99552287, 13.66148136, 12.09096809, 12.88322443,
       15.25440806, 15.53572979, 14.0433635 , 14.49426396, 17.18744147,
       14.1787126 , 16.7281901 , 15.62246614, 15.58467428, 17.52747053,
       14.57324714, 14.88133639, 16.0330997 , 14.59774665, 17.87926798,
       14.12463855, 13.8446561 , 15.45394052, 15.01597274, 14.7739403 ,
       15.7092621 , 14.61541714, 14.45843496, 14.81190418, 14.25014565,
       17.07205859, 16.03388896, 15.84340388, 14.86508928, 14.93076276,
       12.4283457 , 14.54665456, 13.05122514, 13.14190951, 13.00001194,
       12.93447952])

In [33]:
new_metadata_df = pd.DataFrame(d)

In [34]:
new_metadata_df.to_csv("/raid/user/JUMP/cpg0004-lincs/metadata/top20_moa_plate_norms_dmso.csv")

In [20]:
len(means[0]), len(plates)

(198, 136)

In [11]:
metadata_df = pd.read_csv("/raid/user/data/JUMP/cpg0004-lincs/metadata/top20_moa_plate_norms.csv")

In [12]:
metadata_df

,Unnamed: 0,Metadata_Plate,DNA_mean,ER_mean,RNA_mean,AGP_mean,Mito_mean,DNA_std,ER_std,RNA_std,...,DNA_phase_mean,ER_phase_mean,RNA_phase_mean,AGP_phase_mean,Mito_phase_mean,DNA_phase_std,ER_phase_std,RNA_phase_std,AGP_phase_std,Mito_phase_std
0,0,SQ00014812,13.426222,27.958689,29.534679,35.328371,24.781234,28.629468,31.738481,31.257489,...,14.410398,14.938265,15.876648,15.946102,16.318696,27.059081,26.794718,27.894380,27.455284,27.922112
1,1,SQ00014813,13.708645,26.903624,30.617022,33.928247,23.685044,29.082375,31.367334,31.812630,...,14.242333,14.979996,16.066585,15.912597,16.229108,27.098202,26.817586,27.975216,27.505364,27.964598
2,2,SQ00014814,14.195807,27.893841,31.408675,38.274189,22.977037,29.452881,31.491778,31.909071,...,14.337612,15.033278,16.104702,16.157912,16.020577,27.129504,26.817530,27.951736,27.692212,28.090902
3,3,SQ00014815,14.004703,28.346260,31.703615,37.032757,23.181861,28.893750,31.560189,31.780028,...,14.314685,15.025761,16.104050,16.005609,16.131941,27.143375,26.860315,27.979521,27.536113,27.952563
4,4,SQ00014816,14.070147,27.522914,30.986115,34.343169,24.381469,29.256228,31.243010,31.615427,...,14.340505,15.001615,16.097324,15.777459,16.253633,27.293115,26.885570,28.021923,27.523335,28.129448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,131,SQ00015229,12.325838,23.115464,25.751535,28.651396,16.835682,27.415513,30.533789,30.741833,...,14.532788,14.959644,15.824762,15.919382,15.486901,26.891688,26.642010,27.792006,27.512480,27.843115
132,132,SQ00015230,13.051898,24.949519,27.806033,30.846102,18.044170,29.005001,32.328646,32.574588,...,14.503597,15.078014,15.778975,15.923557,15.775772,27.153493,26.902327,27.996177,27.553470,28.017863
133,133,SQ00015231,13.236427,25.967194,29.032115,32.516315,19.645312,28.911721,32.143647,32.635895,...,14.554367,15.057958,15.920864,16.048778,16.044841,27.177121,26.977909,27.928201,27.575855,28.062428
134,134,SQ00015232,12.945863,25.134118,28.063141,32.028293,18.771833,28.882485,32.294134,32.576808,...,14.506498,15.050755,15.859546,16.042636,16.005382,27.179807,26.917846,27.918886,27.623885,28.085058
135,135,SQ00015233,12.935315,25.406369,27.786265,33.280823,18.347297,29.126664,32.898230,32.884611,...,14.573149,15.142802,15.871961,16.169404,15.877299,27.248912,27.041851,27.940530,27.694628,28.070262

# RXRX1

In [25]:
df = pd.read_csv("/raid/user/data/RXRX1/rxrx1/plate_negative_control_norm.csv")
df["plate"].nunique()

64

In [11]:
class ImagesDS(BaseSet):
    def __init__(self, dataset_params, csv_file, img_dir, extend_train_set=False, mode='train', site=1, channels=[1,2,3,4,5,6], batch_size = None):
        if mode == "eval":
            mode = "test"
        self.mode = mode
        self.attr_from_dict(dataset_params) 
        self.name = self.__class__.__name__
        self.extend_train_set = extend_train_set
        df            = pd.read_csv(csv_file)
        self.n_classes     = 1139 
        self.n_batches     = len(df.experiment.unique())
        self.batch_size = batch_size
        df            = df[(df.dataset == mode) & (df.cell_type == "HUVEC")]
        if (self.mode == 'train') and (not self.extend_train_set):
            df = df
        elif (self.mode == 'train') and (self.extend_train_set):
            df = pd.concat([df]*20)
        self.df       = df
        self.records  = df.to_records(index=False)
        self.channels = channels
        self.site     = site
        self.mode     = mode
        self.img_dir  = img_dir
        self.len      = self.df.shape[0]
        
        self.img_channels  = 6
        self.img_size      = 512
        self.is_multiclass = False
        self.labels_to_int = {str(x): x for x       in range(self.n_classes)}
        self.int_to_labels = {int(val):key       for key,val in self.labels_to_int.items()}   
        self.labels_to_int_batch = {str(x): int(x[-2:]) for x       in df.experiment.unique()}
        self.int_to_labels_batch = {val:key             for key,val in self.labels_to_int_batch.items()}   
        self.transform = Compose([Resize(512, interpolation=InterpolationMode.BICUBIC)])

    @staticmethod
    def _load_img_as_tensor(file_name):
        with Image.open(file_name) as img:
            return ToTensor()(img)
    def _get_img_path(self, index, channel):
        experiment, well, plate, site = self.records[index].experiment, self.records[index].well, self.records[index].plate, self.records[index].site
        return '/'.join([self.img_dir,experiment,f'Plate{plate}',f'{well}_s{site}_w{channel}.png'])
    def __getitem__(self, index):
        return self.read_sample(index)

    def __len__(self):
        """
        Total number of samples in the dataset
        """
        return self.len
        
    def read_sample(self, index):
        paths = [self._get_img_path(index, ch) for ch in self.channels]
        X = torch.cat([self._load_img_as_tensor(img_path) for img_path in paths]).type(torch.FloatTensor)
        X = self.transform(X)
        X = X.transpose(0,2)
        y     = int(self.records[index].sirna_id)
        key   = int(self.records[index].experiment[-2:]) - 1
        plate = key*10+int(self.records[index].plate) 
        return X,y,key,plate
        

data_params = {"data_location" : "./data",
                    "dataset": "RXRX1A",
                    "download_data" : True,
                    "validation_size" : 0
                  }

csv_file="/raid/user/data/RXRX1/rxrx1/metadata.csv" # /PATH/TO/METDADATA/metadata.csv
img_dir="/raid/user/data/RXRX1/rxrx1/images" # /PATH/TO/IMAGES
hdf5_path = '/storage/user/datasets/RXRX1/rxrx1/RXRX1_large_plate_info_corrected_size.hdf5' # /PATH/TO/H5py/STORAGE/RXRX1_large_plate_info_corrected_size.hdf5

data_train = ImagesDS(dataset_params=data_params,mode="train", csv_file=csv_file, img_dir=img_dir)
data_test  = ImagesDS(dataset_params=data_params,mode="test", csv_file=csv_file, img_dir=img_dir)

num_train_samples = len(data_train)
num_test_samples  = len(data_test)

train_shape = (num_train_samples, 512, 512, 6)
test_shape  = (num_test_samples , 512, 512, 6)

total_size  =  num_train_samples + num_test_samples
total_shape = (total_size,  512, 512, 6)

In [40]:
metadata = pd.read_csv(csv_file)
metadata

,site_id,well_id,cell_type,dataset,experiment,plate,well,site,well_type,sirna,sirna_id
0,HEPG2-08_1_B02_1,HEPG2-08_1_B02,HEPG2,test,HEPG2-08,1,B02,1,negative_control,EMPTY,1138
1,HEPG2-08_1_B02_2,HEPG2-08_1_B02,HEPG2,test,HEPG2-08,1,B02,2,negative_control,EMPTY,1138
2,HEPG2-08_1_B03_1,HEPG2-08_1_B03,HEPG2,test,HEPG2-08,1,B03,1,treatment,s21721,855
3,HEPG2-08_1_B03_2,HEPG2-08_1_B03,HEPG2,test,HEPG2-08,1,B03,2,treatment,s21721,855
4,HEPG2-08_1_B04_1,HEPG2-08_1_B04,HEPG2,test,HEPG2-08,1,B04,1,treatment,s20894,710
...,...,...,...,...,...,...,...,...,...,...,...
125505,U2OS-03_4_O21_2,U2OS-03_4_O21,U2OS,train,U2OS-03,4,O21,2,treatment,s20367,824
125506,U2OS-03_4_O22_1,U2OS-03_4_O22,U2OS,train,U2OS-03,4,O22,1,treatment,s195079,328
125507,U2OS-03_4_O22_2,U2OS-03_4_O22,U2OS,train,U2OS-03,4,O22,2,treatment,s195079,328
125508,U2OS-03_4_O23_1,U2OS-03_4_O23,U2OS,train,U2OS-03,4,O23,1,treatment,s21454,509
125509,U2OS-03_4_O23_2,U2OS-03_4_O23,U2OS,train,U2OS-03,4,O23,2,treatment,s21454,509

In [13]:
num_train_samples, num_test_samples

(39342, 19708)

In [17]:
hdf5_path = '/raid/user/data/RXRX1/RXRX1_large_plate_info_corrected_size.hdf5'
read_mode = "train"
split_number = 1
mode = "train"
fb = False
subset_data = False
subset_strategy = ""
drop_treatment_duplicates = False
drop_treatment_duplicates_keep_controlls = False

In [18]:
def get_dataframe():        
    with h5py.File(hdf5_path, 'r') as full_data:

        h5_file_y = np.array(full_data[read_mode + '_labels'])
        h5_file_b = np.array(full_data[read_mode + '_batch' ])
        h5_file_p = np.array(full_data[read_mode + '_plate' ])
        length = len(h5_file_y)
        df = pd.DataFrame({'label_name': h5_file_y[:], 'label': h5_file_y[:], 'plate': h5_file_p[:], 'domain': h5_file_b[:]}, columns=['label_name', 'label', 'plate', 'domain'])

        df["img_path"] = df.index

    all_domains = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
    splits =   {1: {"train":all_domains[ 0:16],                    "eval": all_domains[16:20], "test": all_domains[20:24]},
                2: {"train":all_domains[ 4:20],                    "eval": all_domains[20:24], "test": all_domains[ 0: 4]},
                3: {"train":all_domains[ 8:24],                    "eval": all_domains[ 0: 4], "test": all_domains[ 4: 8]},
                4: {"train":all_domains[12:24]+all_domains[ 0: 4], "eval": all_domains[ 4: 8], "test": all_domains[ 8:12]},
                5: {"train":all_domains[16:24]+all_domains[ 0: 8], "eval": all_domains[ 8:12], "test": all_domains[12:16]},
                6: {"train":all_domains[20:24]+all_domains[ 0:12], "eval": all_domains[12:16], "test": all_domains[16:20]}}

    
    df = df[df.domain.isin(splits[split_number][mode])]    
    print(splits[split_number][mode])

    if mode == "train" and not fb:
        if subset_data:
            if self.subset_strategy == "only_controls":

                df = df[~(df.label_name < 1108)] # Only select controls for training
            elif subset_strategy == "only_treatments":
                df = df[(df.label_name < 1108)]  # Only select treatments for training
            elif subset_strategy == "only_treatments_half_as_many":
                df = df[(df.label_name < 1108)].drop_duplicates(subset=["label","plate"])  # Only select treatments for training
            elif subset_strategy == "only_treatments_half_as_many_with_controls":
                unint = df[(df.label_name < 1108)].drop_duplicates(subset=["label","plate"]).index # Keeps all the controlls and one replicate per plate and label

                print("NUMBER OF DROPED INDEXES", len(unint))

                df    = df.drop(unint)
                print("SIZE AFTER DROPPING", df.shape)

            elif self.subset_strategy == "only_half_as_many_treatments_with_controls":
                drop_ids = [i for i in df[(df.label_name < 1108)].label_name.unique() if i%2==0]
                df = df[~df.label_name.isin(drop_ids)]

    if drop_treatment_duplicates:
        df = df[~(df.label_name < 1108)].drop_duplicates(subset=["label","plate"])
    if drop_treatment_duplicates_keep_controlls:
        unint = df[(df.label_name < 1108)].drop_duplicates(subset=["label","plate"]).index # Keeps all the controlls and one replicate per plate and label
        df    = df.drop(unint)

    print("MAXIMUM PLATE NUMBER: ", df.plate.unique())
    
    return df

In [52]:
df = get_dataframe()

In [53]:
df["label"].nunique()

1139

In [29]:
h5_path_x = hdf5_path
h5_file_x = h5py.File(h5_path_x, 'r')[read_mode + '_img']
h5_file_plate = h5py.File(h5_path_x, 'r')[read_mode + '_plate']

In [30]:
df["plate"].nunique()

96

In [42]:
mean_columns = ["mean_" + str(x) for x in range(6)]
std_columns  = ["std_"  + str(x) for x in range(6)]

mean, std, plates = [], [], []
for p in df["plate"].unique():
    print(p)
    means = [[] for i in range(6)]
    stds = [[] for i in range(6)]
    
    for idx, row in df[df["plate"] == p].iterrows():
        if row["label"] == 1138:
            img_path = row["img_path"]
            img = h5_file_x[int(img_path)]
            plate = h5_file_plate[int(img_path)]
            mean_0, std_0 = np.mean(img[..., 0]), np.std(img[..., 0])
            mean_1, std_1 = np.mean(img[..., 1]), np.std(img[..., 1])
            mean_2, std_2 = np.mean(img[..., 2]), np.std(img[..., 2])
            mean_3, std_3 = np.mean(img[..., 3]), np.std(img[..., 3])
            mean_4, std_4 = np.mean(img[..., 4]), np.std(img[..., 4])
            mean_5, std_5 = np.mean(img[..., 5]), np.std(img[..., 5])

            means[0].append(mean_0)
            stds[0].append(std_0)
            means[1].append(mean_1)
            stds[1].append(std_1)
            means[2].append(mean_2)
            stds[2].append(std_2)
            means[3].append(mean_3)
            stds[3].append(std_3)
            means[4].append(mean_4)
            stds[4].append(std_4)
            means[5].append(mean_5)
            stds[5].append(std_5)
            
    mean.append(np.array(means).mean(axis=1))
    std.append(np.array(stds).mean(axis=1))
    plates.append(p)

1
2
3
4
11
12
13
14
21
22
23
24
31
32
33
34
41
42
43
44
51
52
53
54
61
62
63
64
71
72
73
74
81
82
83
84
91
92
93
94
101
102
103
104
111
112
113
114
121
122
123
124
131
132
133
134
141
142
143
144
151
152
153
154
161
162
163
164
171
172
173
174
181
182
183
184
191
192
193
194
201
202
203
204
211
212
213
214
221
222
223
224
231
232
233
234

In [47]:
mean = np.array(mean)
std = np.array(std)

mean = mean.transpose()
std = std.transpose()

d = {
    "plates": plates,
    "mean_0": mean[0],
    "mean_1": mean[1],
    "mean_2": mean[2],
    "mean_3": mean[3],
    "mean_4": mean[4],
    "mean_5": mean[5],
    "std_0": std[0],
    "std_1": std[1],
    "std_2": std[2],
    "std_3": std[3],
    "std_4": std[4],
    "std_5": std[5],
}

In [61]:
df["plate"] = df["plates"]

In [65]:
df = pd.DataFrame(d)
df.to_csv('/raid/user/data/RXRX1/plate_negative_control_norm.csv')

In [66]:
df = pd.read_csv('/raid/user/data/RXRX1/plate_negative_control_norm.csv')
df

,Unnamed: 0,plates,mean_0,mean_1,mean_2,mean_3,mean_4,mean_5,std_0,std_1,std_2,std_3,std_4,std_5
0,0,1,5.076746,22.414171,11.353750,12.761932,2.689083,15.342363,6.248371,18.323926,4.483372,9.595654,3.222820,7.804344
1,1,2,5.584234,24.781311,12.234890,14.039787,2.174679,17.224792,7.183184,19.071639,4.584674,10.466397,2.073625,8.521309
2,2,3,5.518858,22.600042,12.476444,13.082191,2.289261,16.048706,6.899788,17.380054,5.041257,9.756586,1.922813,7.911075
3,3,4,5.271481,21.565147,11.477266,12.314405,2.175409,14.925558,6.802439,15.764627,4.582590,8.644633,1.829981,6.699891
4,4,11,5.104643,20.711044,9.203665,11.104469,2.015215,12.681240,7.330720,14.583998,3.387271,7.506257,1.903849,5.033923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,91,224,6.300005,14.697165,8.259589,7.118806,6.002778,5.893213,4.787445,9.597908,2.800465,4.288787,4.234490,1.778829
92,92,231,5.546413,21.623158,7.746975,9.987010,6.507708,6.153636,3.945720,11.582338,2.670652,4.957349,5.092795,1.952494
93,93,232,6.822630,20.870371,8.136842,10.074770,6.778649,6.561309,5.030002,11.711453,3.734686,5.288137,5.341186,2.536393
94,94,233,6.643969,21.816842,7.694051,9.033996,5.992930,6.201934,4.990626,12.964124,2.972437,4.972098,4.540304,2.040694
95,95,234,5.596926,21.175089,7.761882,9.991797,7.295756,6.341455,3.980951,11.670655,2.605003,5.068931,5.131294,1.968470

In [68]:
df["plate"] = df["plates"]
df.to_csv('/raid/user/data/RXRX1/plate_negative_control_norm.csv')

In [69]:
df = pd.read_csv('/raid/user/data/RXRX1/plate_negative_control_norm.csv')
df

,Unnamed: 0.1,Unnamed: 0,plates,mean_0,mean_1,mean_2,mean_3,mean_4,mean_5,std_0,std_1,std_2,std_3,std_4,std_5,plate
0,0,0,1,5.076746,22.414171,11.353750,12.761932,2.689083,15.342363,6.248371,18.323926,4.483372,9.595654,3.222820,7.804344,1
1,1,1,2,5.584234,24.781311,12.234890,14.039787,2.174679,17.224792,7.183184,19.071639,4.584674,10.466397,2.073625,8.521309,2
2,2,2,3,5.518858,22.600042,12.476444,13.082191,2.289261,16.048706,6.899788,17.380054,5.041257,9.756586,1.922813,7.911075,3
3,3,3,4,5.271481,21.565147,11.477266,12.314405,2.175409,14.925558,6.802439,15.764627,4.582590,8.644633,1.829981,6.699891,4
4,4,4,11,5.104643,20.711044,9.203665,11.104469,2.015215,12.681240,7.330720,14.583998,3.387271,7.506257,1.903849,5.033923,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,91,91,224,6.300005,14.697165,8.259589,7.118806,6.002778,5.893213,4.787445,9.597908,2.800465,4.288787,4.234490,1.778829,224
92,92,92,231,5.546413,21.623158,7.746975,9.987010,6.507708,6.153636,3.945720,11.582338,2.670652,4.957349,5.092795,1.952494,231
93,93,93,232,6.822630,20.870371,8.136842,10.074770,6.778649,6.561309,5.030002,11.711453,3.734686,5.288137,5.341186,2.536393,232
94,94,94,233,6.643969,21.816842,7.694051,9.033996,5.992930,6.201934,4.990626,12.964124,2.972437,4.972098,4.540304,2.040694,233
95,95,95,234,5.596926,21.175089,7.761882,9.991797,7.295756,6.341455,3.980951,11.670655,2.605003,5.068931,5.131294,1.968470,234